export const FILTER_TOPICS = "FILTER_TOPICS";

export const FETCH_TOPICS_REQUESTED = "FETCH_TOPICS_REQUESTED";
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
export const FETCH_TOPICS_ERROR = "FETCH_TOPICS_ERROR";

export const FETCH_TUTORIALS_REQUESTED = "FETCH_TUTORIALS_REQUESTED";
export const FETCH_TUTORIALS_SUCCESS = "FETCH_TUTORIALS_SUCCESS";
export const FETCH_TUTORIALS_ERROR = "FETCH_TUTORIALS_ERROR";

export const FETCH_TOPIC_DETAILS_REQUESTED = "FETCH_TOPIC_DETAILS_REQUESTED";
export const FETCH_TOPIC_DETAILS_SUCCESS = "FETCH_TOPIC_DETAILS_SUCCESS";
export const FETCH_TOPIC_DETAILS_ERROR = "FETCH_TOPIC_DETAILS_ERROR";
