export const TUTORIALS_REQUESTED = "TUTORIALS_REQUESTED";
export const FETCH_TUTORIALS_SUCCESS = "FETCH_TUTORIALS_SUCCESS";
export const FOLLOW_TOPIC = "FOLLOW_TOPIC";
export const UNFOLLOW_TOPIC = "UNFOLLOW_TOPIC";
export const SEARCH_TOPIC = "SEARCH_TOPIC";
export const TOPICS_REQUESTED = "TOPICS_REQUESTED";
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
